move the util check func into common.sh so that we can call it early

diff --git a/procmap b/procmap
--- a/procmap
+++ b/procmap
@@ -58,6 +58,10 @@ source ${PFX}/config || {
  echo "${name}: fatal: could not source configuration in file '${PFX}/config', aborting..."
  exit 1
 }
+source ${PFX}/common.sh || {
+ echo "${name}: fatal: could not source file '${PFX}/common.sh', aborting..."
+ exit 1
+}
 source ${PFX}/lib_procmap.sh || {
  echo "${name}: fatal: could not source ${PFX}/lib_procmap.sh , aborting..."
  exit 1
@@ -171,14 +175,6 @@ show_selected_opt()
   fg_yellow
   printf "%s\n" "$@"
   color_reset
-}
-
-verify_utils_present()
-{
-check_deps_fatal "getconf bc make gcc kmod grep awk sed kill readlink head tail \
-cut cat tac sort wc ldd file"
-check_deps_warn "sudo tput ps smem"
-[ ! -d /proc ] && FatalError "proc fs not available or not mounted? Aborting..."
 }
 
 
